version: '3.3'

services:
  web:
    restart: always
    container_name: web
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./data:/var/lib/sqlite/data
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
