version: '3.3'

services:
  web:
    restart: always
    container_name: web
    build: .
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db
    env_file:
      - .env


  redis:
    image: redis:7-alpine


  db:
    restart: always
    image: postgres:15-alpine
    container_name: db
    ports:
      - "5431:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: Chat_db
      POSTGRES_USER: jobir
      POSTGRES_PASSWORD: 5Noyabr2022
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
  
  # nginx:
  #   restart: unless-stopped
  #   image: nginx
  #   container_name: web_nginx
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./staticfiles:/usr/src/app/staticfiles
  #     - ./mediafiles:/usr/src/app/mediafiles
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - web